{{- if not (and .Values.st2.packs.volumes.enabled .Values.st2.packs.volumes.configs) -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-st2-pack-configs
  annotations:
    description: Custom StackStorm pack configs, shipped in '/opt/stackstorm/configs/'
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.st2.packs.configs | indent 2 }}
{{- end -}}
