# Notify users about breaking change regarding secrets, to not destroy current installations
{{- $deprecated_ssh_key := (default (dict) (default (dict) .Values.secrets).st2).ssh_key }}
{{- if $deprecated_ssh_key }}
{{- fail "Please update your values! The ssh_key value moved from secrets.st2.* to st2.*" }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-st2-ssh
  annotations:
    description: StackStorm SSH secret key for 'stanley' user, used to run actions on remote machines
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  # SSH private key for the 'stanley' system user ('system_user.ssh_key_file' in st2.conf).
  private_key: {{ required "Secret 'st2.ssh_key' is required for StackStorm system user!" .Values.st2.ssh_key | b64enc | quote }}
