{{- range .Values.adhoc_secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  annotations:
    description: Custom Secret for StackStorm - {{ .description }}
  labels:
    app: st2
    tier: backend
    vendor: stackstorm
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
{{- end }}
